// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef images_h
#define images_h
#include <efltk/Fl.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Box.h>
#if !HAVE_PNG
#endif
#include <efltk/Fl_Button.h>
Fl_Window* make_window();
int main(int argc, char *argv[]);
#endif
