// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef image_loader_h
#define image_loader_h
#include <efltk/Fl.h>
#include <efltk/Fl_Double_Window.h>
#include <efltk/Fl_Box.h>
extern Fl_Box* imbox;
extern Fl_Box* filename_box;
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_File_Dialog.h>
#include <efltk/Fl_Divider.h>
Fl_Double_Window* make_window();
int main(int argc, char *argv[]);
#endif
