// generated by Fast Light User Interface Designer (fluid) version 2.0001

#ifndef inactive_h
#define inactive_h
#include <efltk/Fl.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Group.h>
extern Fl_Group* the_group;
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Check_Button.h>
#include <efltk/Fl_Slider.h>
#include <efltk/Fl_Input.h>
#include <efltk/Fl_Input_Browser.h>
#include <efltk/Fl_Item.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Value_Input.h>
#include <efltk/Fl_Scrollbar.h>
#endif
