// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef preferences_h
#define preferences_h
#include <efltk/Fl.h>
#include <efltk/Fl_Config.h>
#include <stdio.h>
extern void readPrefs();
extern void writePrefs();
#include <efltk/Fl_Window.h>
extern void closeWindowCB(Fl_Window*, void*);
extern Fl_Window* myWindow;
#include <efltk/Fl_Button.h>
extern void closeWindowCB(Fl_Button*, void*);
extern void saveAndCloseWindowCB(Fl_Button*, void*);
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Input.h>
extern Fl_Input* wAlarm;
#include <efltk/Fl_Choice.h>
extern Fl_Choice* wAmPm;
#include <efltk/Fl_Item.h>
extern Fl_Choice* wWear;
#include <efltk/Fl_Check_Button.h>
extern Fl_Check_Button* wShower;
extern Fl_Check_Button* wShave;
extern Fl_Check_Button* wBrush;
#include <efltk/Fl_Round_Button.h>
extern Fl_Round_Button* wLeft;
extern Fl_Round_Button* wRight;
#include <efltk/Fl_Box.h>
extern Fl_Choice* wDrink;
extern Fl_Check_Button* wMilk;
extern Fl_Choice* wBread;
extern Fl_Check_Button* wButter;
#include <efltk/Fl_Int_Input.h>
extern Fl_Int_Input* wEggs;
#include <efltk/Fl_Value_Slider.h>
extern Fl_Value_Slider* wMinutes;
extern Fl_Input* wPaper;
void readPrefs();
void writePrefs();
#endif
