// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef resize_h
#define resize_h
#include <efltk/Fl.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Box.h>
#endif
