// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef resizable_h
#define resizable_h
#include <efltk/Fl.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Menu_Bar.h>
extern Fl_Menu_Bar* menu;
#include <efltk/Fl_Item.h>
#include <efltk/Fl_Item_Group.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Group.h>
#endif
