// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef tabs_h
#define tabs_h
#include <efltk/Fl.h>
#include <efltk/Fl_Window.h>
extern Fl_Window* foo_window;
#include <efltk/Fl_Tabs.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Input.h>
#include <efltk/Fl_Wordwrap_Input.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Clock.h>
#include <stdlib.h>
#include <efltk/Fl_Return_Button.h>
#endif
