// generated by Fast Light User Interface Designer (fluid) version 2.0003

#ifndef valuators_h
#define valuators_h
#include <efltk/Fl.h>
#include <efltk/Fl_Window.h>
#include <stdio.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Slider.h>
extern void callback(Fl_Slider*, void*);
#include <efltk/Fl_Value_Input.h>
extern void callback(Fl_Value_Input*, void*);
#include <efltk/Fl_Scrollbar.h>
extern void callback(Fl_Scrollbar*, void*);
#include <efltk/Fl_Value_Slider.h>
extern void callback(Fl_Value_Slider*, void*);
#include <efltk/Fl_Roller.h>
extern void callback(Fl_Roller*, void*);
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Dial.h>
extern void callback(Fl_Dial*, void*);
#include <efltk/Fl_Value_Output.h>
#endif
