// generated by Fast Light User Interface Designer (fluid) version 2.0003

#include "Main.h"

int main(int ac,char *av) {
  SciCalc *calc = new SciCalc();
  	calc->run();
  	delete calc;
  	return 0;
}
