include ../../makeinclude

all:

install: install_headers

install_headers:
	@mkdir -p $(includedir)/efltk/db
	@cp *.h  $(includedir)/efltk/db
	@chmod 644 $(includedir)/efltk/db/*
	@chmod 755 $(includedir)/efltk/db
