include ../../makeinclude

all:

install: install_headers

install_headers:
	@mkdir -p $(includedir)/efltk/net
	@cp *.h  $(includedir)/efltk/net
	@chmod 644 $(includedir)/efltk/net/*
	@chmod 755 $(includedir)/efltk/net
