// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef about_panel_h
#define about_panel_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Double_Window.h>
extern Fl_Double_Window* about_panel;
#include <efltk/Fl_Group.h>
extern Fl_Group* display_group;
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Button.h>
extern Fl_Box* copyright_box;
#include <efltk/Fl_Return_Button.h>
Fl_Double_Window* make_about_panel(const char *copyright);
#endif
