// generated by Extended Fast Light User Interface Designer (eFluid) version 2.0003

#ifndef _ABOUT_PANEL_H_
#define _ABOUT_PANEL_H_

#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Return_Button.h>

extern Fl_Window* about_panel;
extern Fl_Group* display_group;
extern Fl_Box* copyright_box;

Fl_Window* make_about_panel(const char *copyright);

#endif
