// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef alignment_panel_h
#define alignment_panel_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
extern Fl_Window* alignment_window;
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Tabs.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Value_Input.h>
extern void alignment_cb(Fl_Value_Input*, long);
extern Fl_Value_Input* horizontal_input;
extern Fl_Value_Input* vertical_input;
extern Fl_Value_Input* snap_input;
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Input.h>
extern void header_input_cb(Fl_Input*, void*);
extern Fl_Input* header_file_input;
extern void code_input_cb(Fl_Input*, void*);
extern Fl_Input* code_file_input;
#include <efltk/Fl_Check_Button.h>
extern void include_H_from_C_button_cb(Fl_Check_Button*, void*);
extern Fl_Check_Button* include_H_from_C_button;
extern bool i18n;
extern Fl_Check_Button* locale;
#include <efltk/Fl_Divider.h>
Fl_Window* make_alignment_window();
#endif
