// generated by Extended Fast Light User Interface Designer (eFluid) version 2.0003

#ifndef _IMAGE_FILE_PANEL_H_
#define _IMAGE_FILE_PANEL_H_

#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_WM.h>
#include <efltk/Fl_Input.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Return_Button.h>


extern Fl_Window* images_dir_window;
extern Fl_Input* images_dir_input;

Fl_Window* make_images_dir_window();

#endif
