// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef image_file_panel_h
#define image_file_panel_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_WM.h>
extern Fl_Window* images_dir_window;
#include <efltk/Fl_Input.h>
extern Fl_Input* images_dir_input;
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_Return_Button.h>
Fl_Window* make_images_dir_window();
#endif
