CPPFILES = fl_odbc.cpp Fl_ODBC_Database.cpp

CFILES =

LIBNAME = libefltk_odbc

# This MUST be included after FILES
DIRS=
EFLTK_TOPDIR = ../../..
include ../../makeinclude_tmpl

# include dependency files if it exist
ifeq (makedepend, $(wildcard makedepend))
include makedepend
endif
