include ../../makeinclude

all:

install: install_headers

install_headers:
	@mkdir -p $(includedir)/efltk/xml
	@cp *.h  $(includedir)/efltk/xml
	@chmod 644 $(includedir)/efltk/xml/*
	@chmod 755 $(includedir)/efltk/xml
