// generated by Fast Light User Interface Designer (fluid) version 2,0003

#include "main_ui.h"

Fl_Main_Window* mainwindow;

Fl_Menu_Bar* menubar;

Fl_Tool_Bar* toolbar;

Fl_Button* tb_quit;

Fl_Button* tb_load;

Fl_Button* tb_save;

Fl_Button* tb_saveas;

Fl_Button* tb_comp;

Fl_Button* tb_extract;

Fl_Group* maingroup;

Fl_Group* info_group;

Fl_Output* prj_output;

Fl_Output* lang_output;

Fl_Output* trans_output;

Fl_Output* email_output;

Fl_Button* modify_button;

Fl_ListView* browser;

Fl_Output* comment_output;

Fl_Multiline_Input* trans_input;

Fl_Multiline_Input* orig_input;

Fl_Button* save_button;

Fl_Check_Button* fin_button;

Fl_Group* statusgroup;

Fl_Box* statusbar;

Fl_Main_Window* main_window() {
  Fl_Main_Window* w;
   {Fl_Main_Window* o = mainwindow = new Fl_Main_Window(700, 455, _("ETranslate"));
    w = o;
     {Fl_Menu_Bar* o = menubar = new Fl_Menu_Bar(0, 0, 700, 25); o->begin();
       {Fl_Item_Group* o = new Fl_Item_Group(_("&File"));
         {Fl_Item* o = new Fl_Item(_("&Load"));
          o->shortcut(0x4006c);
          o->user_data((void*)(LOAD));
        }
         {Fl_Item* o = new Fl_Item(_("&Save"));
          o->shortcut(0x40073);
          o->user_data((void*)(SAVE));
        }
         {Fl_Item* o = new Fl_Item(_("Save &As"));
          o->shortcut(0x40061);
          o->user_data((void*)(SAVEAS));
        }
         {Fl_Divider* o = new Fl_Divider(0, 0, 0, 2);
        }
         {Fl_Item* o = new Fl_Item(_("&Quit"));
          o->shortcut(0x40071);
          o->user_data((void*)(QUIT));
        }
        o->end();
      }
       {Fl_Item_Group* o = new Fl_Item_Group(_("&Help"));
         {Fl_Item* o = new Fl_Item(_("&About"));
          o->user_data((void*)(ABOUT));
        }
        menubar->right_layout(o);
        o->end();
      }
      o->end();
    }
     {Fl_Tool_Bar* o = toolbar = new Fl_Tool_Bar(0, 25, 700, 40);
       {Fl_Button* o = tb_quit = new Fl_Button(5, 5, 32, 32, _("Quit"));
        o->label_size(10);
        o->tooltip(_("Quit etranslate."));
      }
       {Fl_Divider* o = new Fl_Divider(40, 6, 10, 30, _("label"));
        o->type(Fl_Divider::VERTICAL);
        o->color((Fl_Color)0xfffffffe);
      }
       {Fl_Button* o = tb_load = new Fl_Button(55, 5, 32, 32, _("Load"));
        o->label_size(10);
        o->align(FL_ALIGN_CLIP);
        o->tooltip(_("Load existing file"));
      }
       {Fl_Button* o = tb_save = new Fl_Button(95, 5, 32, 32, _("Save"));
        o->label_size(10);
        o->align(FL_ALIGN_CLIP);
        o->tooltip(_("Save file"));
      }
       {Fl_Button* o = tb_saveas = new Fl_Button(135, 5, 40, 32, _("Save As"));
        o->label_size(10);
        o->align(FL_ALIGN_CLIP);
      }
       {Fl_Divider* o = new Fl_Divider(175, 6, 10, 30, _("label"));
        o->type(Fl_Divider::VERTICAL);
        o->color((Fl_Color)0xfffffffe);
      }
       {Fl_Button* o = tb_comp = new Fl_Button(190, 5, 45, 32, _("Compile"));
        o->label_size(10);
        o->align(FL_ALIGN_CLIP);
        o->tooltip(_("Compile to binary format"));
      }
       {Fl_Button* o = tb_extract = new Fl_Button(240, 5, 45, 32, _("Extract"));
        o->label_size(11);
        o->align(192);
      }
      o->spacing(3);
      o->end();
    }
     {Fl_Group* o = maingroup = new Fl_Group(0, 64, 700, 366);
       {Fl_Group* o = info_group = new Fl_Group(0, 0, 700, 65);
         {Fl_Group* o = new Fl_Group(5, 5, 630, 55);
          o->box(FL_BORDER_BOX);
           {Fl_Output* o = prj_output = new Fl_Output(80, 10, 210, 20, _("Project:"));
            o->box(FL_NO_BOX);
            o->text_font(o->text_font()->bold());
          }
           {Fl_Output* o = lang_output = new Fl_Output(80, 30, 210, 20, _("Language:"));
            o->box(FL_NO_BOX);
            o->text_font(o->text_font()->bold());
          }
           {Fl_Output* o = trans_output = new Fl_Output(385, 10, 240, 20, _("Translator:"));
            o->box(FL_NO_BOX);
            o->text_font(o->text_font()->bold());
          }
           {Fl_Output* o = email_output = new Fl_Output(385, 30, 240, 20, _("Email:"));
            o->box(FL_NO_BOX);
            o->text_font(o->text_font()->bold());
          }
           {Fl_Box* o = new Fl_Box(290, 5, 155, 45);
            o->parent()->resizable(o);
          }
          o->parent()->resizable(o);
          o->end();
        }
         {Fl_Button* o = modify_button = new Fl_Button(640, 5, 55, 55, _("Modify"));
          o->tooltip(_("Modify project information"));
        }
        o->end();
      }
       {Fl_ListView* o = browser = new Fl_ListView(0, 65, 254, 300); o->begin();
        o->button_box(FL_BORDER_BOX);
        o->button_color((Fl_Color)0xe7e7e700);
        o->add_column("Original",125);
        o->add_column("Translation",125);
        o->draw_stripes(true);
        o->end();
      }
       {Fl_Group* o = new Fl_Group(255, 65, 445, 301);
         {Fl_Group* o = new Fl_Group(0, 1, 445, 30);
           {Fl_Output* o = comment_output = new Fl_Output(0, 0, 445, 25, _("Comment"));
            o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
            o->parent()->resizable(o);
          }
          o->end();
        }
         {Fl_Group* o = new Fl_Group(0, 30, 445, 241);
           {Fl_Multiline_Input* o = trans_input = new Fl_Multiline_Input(0, 136, 445, 105, _("Translation"));
            o->type(4);
            o->align(FL_ALIGN_TOP | FL_ALIGN_LEFT);
            o->wordwrap(1);
          }
           {Fl_Multiline_Input* o = orig_input = new Fl_Multiline_Input(0, 15, 445, 105, _("Original"));
            o->type(4);
            o->align(FL_ALIGN_TOP | FL_ALIGN_LEFT);
            o->readonly(true);
            o->wordwrap(1);
          }
           {Fl_Box* o = new Fl_Box(225, 16, 20, 225);
            o->parent()->resizable(o);
          }
          o->parent()->resizable(o);
          o->end();
        }
         {Fl_Group* o = new Fl_Group(0, 271, 445, 30);
           {Fl_Button* o = save_button = new Fl_Button(280, 2, 160, 25, _("Save/Next (CTRL+N)"));
            o->shortcut(0x4006e);
          }
           {Fl_Check_Button* o = fin_button = new Fl_Check_Button(5, 2, 270, 25, _("&Finished (CTRL+F)"));
            o->shortcut(0x40066);
            o->tooltip(_("Mark translation as finished.\nOnly finished translations are compiled to bin\
ary."));
            o->parent()->resizable(o);
          }
          o->end();
        }
        o->parent()->resizable(o);
        o->end();
      }
      o->end();
    }
     {Fl_Group* o = statusgroup = new Fl_Group(0, 430, 700, 25);
       {Fl_Box* o = statusbar = new Fl_Box(0, 2, 700, 21, _("No file loaded.."));
        o->box(FL_BORDER_BOX);
        o->align(68|FL_ALIGN_INSIDE);
        o->parent()->resizable(o);
      }
      o->end();
    }
    o->size_range(o->w(), o->h());
    o->end();
  }
  mainwindow->menu(menubar);
  mainwindow->toolbar(toolbar);
  mainwindow->view(maingroup);
  mainwindow->status(statusgroup);
  return  w;
}

Fl_Multiline_Input* info_comment;

Fl_Input* info_prjname;

Fl_Input* info_prjversion;

Fl_Output* info_startdate;

Fl_Output* info_moddate;

Fl_Input* info_trans;

Fl_Input* info_email;

Fl_Input* info_lang;

Fl_Button* info_cancel;

Fl_Button* info_ok;

Fl_Window* modify_window() {
  Fl_Window* w;
   {Fl_Window* o = new Fl_Window(390, 260, _("Project Information"));
    w = o;
     {Fl_Tabs* o = new Fl_Tabs(5, 5, 380, 211);
       {Fl_Group* o = new Fl_Group(0, 22, 380, 189, _("Information"));
         {Fl_Multiline_Input* o = info_comment = new Fl_Multiline_Input(110, 3, 265, 55, _("Comment:"));
          o->type(4);
          o->wordwrap(1);
        }
        info_prjname = new Fl_Input(110, 63, 265, 25, _("Project Name:"));
        info_prjversion = new Fl_Input(110, 93, 265, 25, _("Project Version:"));
         {Fl_Output* o = info_startdate = new Fl_Output(110, 123, 265, 25, _("Start Date:"));
          o->color(fl_lighter(o->parent()->color()));
        }
         {Fl_Output* o = info_moddate = new Fl_Output(110, 153, 265, 25, _("Last Modified:"));
          o->color(fl_lighter(o->parent()->color()));
        }
        o->end();
      }
       {Fl_Group* o = new Fl_Group(0, 20, 380, 190, _("Translator"));
        o->hide();
        info_trans = new Fl_Input(110, 10, 265, 25, _("Translator:"));
        info_email = new Fl_Input(110, 45, 265, 25, _("E-Mail:"));
        info_lang = new Fl_Input(110, 80, 265, 25, _("Language:"));
        o->end();
      }
      o->end();
    }
    new Fl_Divider(5, 215, 380, 15, _("label"));
    info_cancel = new Fl_Button(315, 230, 70, 25, _("Cancel"));
    info_ok = new Fl_Button(235, 230, 70, 25, _("OK"));
    o->end();
  }
  return  w;
}
