// generated by Extended Fast Light User Interface Designer (eFluid) version 2.0003

#ifndef _MAIN_UI_H_
#define _MAIN_UI_H_

#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include <efltk/Fl_Main_Window.h>
#include <efltk/Fl_Menu_Bar.h>
#include <efltk/Fl_Item_Group.h>
#include <efltk/Fl_Item.h>
#include <efltk/Fl_Divider.h>
#include <efltk/Fl_Tool_Bar.h>
#include <efltk/Fl_Button.h>
#include <efltk/Fl_Group.h>
#include <efltk/Fl_Output.h>
#include <efltk/Fl_Box.h>
#include <efltk/Fl_ListView.h>
#include <efltk/Fl_Multiline_Input.h>
#include <efltk/Fl_Check_Button.h>
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Tabs.h>
#include <efltk/Fl_Input.h>

extern Fl_Main_Window* mainwindow;
extern Fl_Menu_Bar* menubar;
extern Fl_Tool_Bar* toolbar;
extern Fl_Button* tb_quit;
extern Fl_Button* tb_load;
extern Fl_Button* tb_save;
extern Fl_Button* tb_saveas;
extern Fl_Button* tb_comp;
extern Fl_Button* tb_extract;
extern Fl_Group* maingroup;
extern Fl_Group* info_group;
extern Fl_Output* prj_output;
extern Fl_Output* lang_output;
extern Fl_Output* trans_output;
extern Fl_Output* email_output;
extern Fl_Button* modify_button;
extern Fl_ListView* browser;
extern Fl_Output* comment_output;
extern Fl_Multiline_Input* trans_input;
extern Fl_Multiline_Input* orig_input;
extern Fl_Button* save_button;
extern Fl_Check_Button* fin_button;
extern Fl_Group* statusgroup;
extern Fl_Box* statusbar;
extern Fl_Multiline_Input* info_comment;
extern Fl_Input* info_prjname;
extern Fl_Input* info_prjversion;
extern Fl_Output* info_startdate;
extern Fl_Output* info_moddate;
extern Fl_Input* info_trans;
extern Fl_Input* info_email;
extern Fl_Input* info_lang;
extern Fl_Button* info_cancel;
extern Fl_Button* info_ok;

#include "globals.h"
Fl_Main_Window* main_window();
Fl_Window* modify_window();

#endif
