// generated by Fast Light User Interface Designer (fluid) version 2,0003

#ifndef main_ui_h
#define main_ui_h
#include <efltk/Fl.h>
#include <efltk/Fl_Locale.h>
#include "globals.h"
#include <efltk/Fl_Main_Window.h>
extern Fl_Main_Window* mainwindow;
#include <efltk/Fl_Menu_Bar.h>
extern Fl_Menu_Bar* menubar;
#include <efltk/Fl_Item_Group.h>
#include <efltk/Fl_Item.h>
#include <efltk/Fl_Divider.h>
#include <efltk/Fl_Tool_Bar.h>
extern Fl_Tool_Bar* toolbar;
#include <efltk/Fl_Button.h>
extern Fl_Button* tb_quit;
extern Fl_Button* tb_load;
extern Fl_Button* tb_save;
extern Fl_Button* tb_comp;
#include <efltk/Fl_Group.h>
extern Fl_Group* maingroup;
#include <efltk/Fl_Output.h>
extern Fl_Output* prj_output;
extern Fl_Output* lang_output;
extern Fl_Output* trans_output;
extern Fl_Output* email_output;
#include <efltk/Fl_Box.h>
extern Fl_Button* modify_button;
#include <efltk/Fl_ListView.h>
extern Fl_ListView* browser;
extern Fl_Output* comment_output;
#include <efltk/Fl_Multiline_Input.h>
extern Fl_Multiline_Input* trans_input;
extern Fl_Multiline_Input* orig_input;
extern Fl_Button* save_button;
#include <efltk/Fl_Check_Button.h>
extern Fl_Check_Button* fin_button;
extern Fl_Group* statusgroup;
extern Fl_Box* statusbar;
Fl_Main_Window* main_window();
#include <efltk/Fl_Window.h>
#include <efltk/Fl_Tabs.h>
extern Fl_Multiline_Input* info_comment;
#include <efltk/Fl_Input.h>
extern Fl_Input* info_prjname;
extern Fl_Input* info_prjversion;
extern Fl_Output* info_startdate;
extern Fl_Output* info_moddate;
extern Fl_Input* info_trans;
extern Fl_Input* info_email;
extern Fl_Input* info_lang;
extern Fl_Button* info_cancel;
extern Fl_Button* info_ok;
Fl_Window* modify_window();
#endif
