CPPFILES = \
	Fl.cpp \
	Fl_Bitmap.cpp \
	Fl_Bmp.cpp \
	Fl_Boxtype.cpp \
	Fl_Config.cpp \
	Fl_Data_Fields.cpp \
	Fl_Data_Source.cpp \
	Fl_Date_Time.cpp \
	Fl_Exception.cpp \
	Fl_Gif.cpp \
	Fl_Group.cpp \
	Fl_Hashs.cpp \
	Fl_Image.cpp \
	Fl_Image_Filter.cpp \
	Fl_Lists.cpp \
	Fl_Maps.cpp \
	Fl_Pixmap.cpp \
	Fl_Renderer.cpp \
	Fl_String.cpp \
	Fl_Style.cpp \
	Fl_Style_Set.cpp \
	Fl_Thread.cpp \
	Fl_Translator.cpp \
	Fl_Util.cpp \
	Fl_Variant.cpp \
	Fl_WM.cpp \
	Fl_Widget.cpp \
	Fl_Window.cpp \
	Fl_Window_fullscreen.cpp \
	Fl_Window_hotspot.cpp \
	Fl_Window_iconize.cpp \
	Fl_Xpm.cpp \
	Fl_abort.cpp \
	Fl_add_idle.cpp \
	Fl_arg.cpp \
	Fl_compose.cpp \
	Fl_display.cpp \
	Fl_get_key.cpp \
	Fl_init.cpp \
	Fl_key_name.cpp \
	Fl_lock.cpp \
	Fl_own_colormap.cpp \
	Fl_visual.cpp \
        KStoUCS.cpp \
	filename_absolute.cpp \
	filename_expand.cpp \
	filename_ext.cpp \
	filename_isdir.cpp \
	filename_list.cpp \
	filename_match.cpp \
	filename_setext.cpp \
	fl_arc.cpp \
	fl_arci.cpp \
	fl_oval_box.cpp \
	fl_plastic_box.cpp \
	fl_round_box.cpp \
	fl_rounded_box.cpp \
	fl_shadow_box.cpp \
	fl_diamond_box.cpp \
	fl_blit.cpp \
	fl_blit_1.cpp \
	fl_blit_a.cpp \
	fl_blit_n.cpp \
	fl_clip.cpp \
	fl_color.cpp \
	fl_converters.cpp \
	fl_cursor.cpp \
	fl_curve.cpp \
	fl_dnd.cpp \
	fl_draw.cpp \
	fl_draw_image.cpp \
	fl_draw_pixmap.cpp \
	fl_font.cpp \
	fl_glyph.cpp \
	fl_labeltype.cpp \
	fl_list_fonts.cpp \
	fl_load_plugin.cpp \
	fl_locale.cpp \
	fl_map.cpp \
	fl_overlay.cpp \
	fl_overlay_visual.cpp \
	fl_rect.cpp \
	fl_rgb.cpp \
	fl_scroll_area.cpp \
	fl_stretch.cpp \
	fl_vertex.cpp \
	fl_theme.cpp

CFILES = \
	fl_utf8.c \
	scandir.c \
	numericsort.c \
	vsnprintf.c

LIBNAME =

# This MUST be included after FILES
DIRS=
EFLTK_TOPDIR = ../..
include ../makeinclude_tmpl

# include dependency files if it exist
ifeq (makedepend, $(wildcard makedepend))
include makedepend
endif
