EFLTK_TOPDIR = ..

DIRS = efluid etranslate ecalc
PROGRAM=
LIBNAME=
include $(EFLTK_TOPDIR)/src/makeinclude_tmpl

uninstall:
	@rm -f $(bindir)/efluid
	@rm -f $(bindir)/etranslate
	@rm -f $(bindir)/ecalc
