CPPFILES = \
	Fl_Adjuster.cpp \
	Fl_Align_Group.cpp \
	Fl_Bar.cpp \
	Fl_Browser.cpp \
	Fl_Box.cpp \
	Fl_Button.cpp \
	Fl_Calendar.cpp \
	Fl_Check_Button.cpp \
	Fl_Choice.cpp \
	Fl_Clock.cpp \
	Fl_Color_Chooser.cpp \
	Fl_Combo_Box.cpp \
	Fl_Date_Time_Input.cpp \
	Fl_Dial.cpp \
	Fl_Dialog.cpp \
	Fl_Directory_DS.cpp \
	Fl_Double_Window.cpp \
	Fl_FileBrowser.cpp \
	Fl_FileInput.cpp \
	Fl_File_Dialog.cpp \
	Fl_Float_Input.cpp \
	Fl_Help_Dialog.cpp \
	Fl_Highlight_Button.cpp \
	Fl_Input.cpp \
	Fl_Input_Browser.cpp \
	Fl_Item.cpp \
	Fl_Light_Button.cpp \
	Fl_ListView.cpp \
	Fl_ListView_Header.cpp \
	Fl_ListView_Item.cpp \
	Fl_MDI_Window.cpp \
	Fl_Main_Window.cpp \
	Fl_Masked_Input.cpp \
	Fl_MDI_Bar.cpp \
	Fl_Memory_DS.cpp \
	Fl_Menu.cpp \
	Fl_Menu_.cpp \
	Fl_Menu_add.cpp \
	Fl_Menu_Bar.cpp \
	Fl_Menu_Button.cpp \
	Fl_Menu_Item.cpp \
	Fl_Menu_Window.cpp \
	Fl_Menu_global.cpp \
	Fl_Multi_Image.cpp \
	Fl_Multi_Tabs.cpp \
	Fl_Numeric_Input.cpp \
	Fl_Output.cpp \
	Fl_Overlay_Window.cpp \
	Fl_Pack.cpp \
	Fl_Popup_Window.cpp \
	Fl_ProgressBar.cpp \
	Fl_Radio_Button.cpp \
	Fl_Repeat_Button.cpp \
	Fl_Return_Button.cpp \
	Fl_Roller.cpp \
	Fl_Scroll.cpp \
	Fl_Scrollbar.cpp \
	Fl_Shaped_Window.cpp \
        Fl_Simple_Html.cpp \
	Fl_Single_Window.cpp \
	Fl_Slider.cpp \
	Fl_Tabs.cpp \
	Fl_Text_Buffer.cpp \
	Fl_Text_Display.cpp \
	Fl_Text_Editor.cpp \
	Fl_Tile.cpp \
        Fl_Tool_Bar.cpp \
	Fl_Tooltip.cpp  \
	Fl_Valuator.cpp \
	Fl_Value_Input.cpp \
	Fl_Value_Slider.cpp \
        Fl_Workspace.cpp \
	fl_ask.cpp \
	fl_engraved_label.cpp \
	fl_show_colormap.cpp \
	fl_symbols.cpp

CFILES =

LIBNAME =

# This MUST be included after FILES
DIRS=
EFLTK_TOPDIR = ../..
include ../makeinclude_tmpl

# include dependency files if it exist
ifeq (makedepend, $(wildcard makedepend))
include makedepend
endif
